deployment:
  tasks:
    - export DEPLOYPATH=/home/smpd9434/public_html/demo.smpn11-depok.sch.id
    - /bin/cp -r * $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;